// shared/functional_burden.js
// =====================================================================
// Functional burden / selection efficacy — per-inversion-candidate
// aggregator (specs_todo/SPEC_functional_burden_per_candidate_v1.md).
//
// SCOPE — the inversion-atlas side is "a thin aggregator, not a
// re-implementation" (spec §1). Producer layers (per-window π, πN/πS,
// π0/π4, VESM, LOF, ROH) are generated by upstream pipelines (e.g.
// catfish-diversity-analysis, unified-ancestry) and exposed through
// the data registries in atlas-core — the same registries the
// Diversity Atlas reads. This module consumes those registry layers,
// aggregates them within a candidate's [start_bp, end_bp], stratifies
// by karyotype, runs Kruskal–Wallis + pairwise Wilcoxon, and emits a
// per-metric verdict + composite tag per spec §3.
//
// All math is NA-tolerant via the shared/stats_helpers and
// shared/wilcoxon machinery.
// =====================================================================

import { median, iqr, kruskalWallis } from './stats_helpers.js';
import { wilcoxonRankSumP } from './wilcoxon.js';

// =====================================================================
// Vocab + defaults
// =====================================================================

/** Spec §3 verdict labels. */
export const FUNCTIONAL_BURDEN_VERDICTS = Object.freeze({
  NEUTRAL:        'neutral',
  INV_ELEVATED:   'inv_elevated',
  INV_DEPLETED:   'inv_depleted',
  HETEROSIS_LIKE: 'heterosis_like',
  MIXED:          'mixed',
  UNDERPOWERED:   'underpowered',
});

/** Spec §3 composite tag labels. */
export const FUNCTIONAL_BURDEN_TAGS = Object.freeze({
  LOAD_RICH: 'load_rich',
  CLEAN:     'clean',
  MIXED:     'mixed',
});

/** Spec §1.6 metric keys (the producer-layer names). */
export const FUNCTIONAL_BURDEN_METRICS = Object.freeze([
  'pi', 'pi_n_pi_s', 'pi0_pi4', 'vesm_burden', 'lof_burden', 'roh_overlap',
]);

/** Metrics that participate in the composite tag (spec §3:
 *  "≥ 3 of {πN/πS, VESM, LOF, ROH}"). */
export const FUNCTIONAL_BURDEN_TAG_METRICS = Object.freeze([
  'pi_n_pi_s', 'vesm_burden', 'lof_burden', 'roh_overlap',
]);

/** Spec §3 thresholds. */
export const FUNCTIONAL_BURDEN_DEFAULTS = Object.freeze({
  kw_p_threshold:        0.05,
  median_equiv_pct:      0.10,   // "all-group medians within ±10%" → neutral
  pairwise_p_threshold:  0.05,
  min_group_n:           5,      // n_min < 5 in any group → underpowered
  tag_threshold:         3,      // ≥3 of {πN/πS, VESM, LOF, ROH}
});

/** Karyotype group labels (spec §2). */
export const KARYOTYPE_GROUPS = Object.freeze(['STD/STD', 'HET', 'INV/INV']);

/** Schema constants for the output object. */
export const FUNCTIONAL_BURDEN_MODULE_VERSION = 'functional_burden_per_candidate_v1.0';

// =====================================================================
// 1. Aggregate per-sample per-window values within a candidate interval
// =====================================================================

/**
 * For a single metric layer (array of per-window records), compute a
 * per-sample mean across the windows that overlap the candidate's
 * `[start_bp, end_bp]` interval.
 *
 * Window record shape:
 *   { start_bp, end_bp, per_sample_values: Array<number> }
 *
 * Returns:
 *   { per_sample_means: Array<number>, n_windows: int }
 *
 * Windows are "overlapping" the candidate if
 *   window.start_bp < candidate.end_bp && window.end_bp > candidate.start_bp
 * (standard half-open overlap test).
 *
 * Missing values (-1 sentinel, NaN, null) are dropped per-window
 * before averaging; samples with no windows contributing → NaN.
 *
 * @param {Array<Object>} per_window_records
 * @param {{start_bp:number, end_bp:number}} candidate
 * @returns {{per_sample_means:number[], n_windows:number}}
 */
export function aggregatePerSampleWithinCandidate(per_window_records, candidate) {
  if (!Array.isArray(per_window_records) || per_window_records.length === 0) {
    return { per_sample_means: [], n_windows: 0 };
  }
  if (!candidate || !Number.isFinite(candidate.start_bp) || !Number.isFinite(candidate.end_bp)) {
    return { per_sample_means: [], n_windows: 0 };
  }
  const cs = candidate.start_bp, ce = candidate.end_bp;
  let n_windows = 0;
  let n_samples = 0;
  // Infer sample count from the first window with per_sample_values.
  for (const w of per_window_records) {
    if (w && Array.isArray(w.per_sample_values)) {
      n_samples = w.per_sample_values.length;
      break;
    }
  }
  const sums = new Float64Array(n_samples);
  const counts = new Int32Array(n_samples);
  for (const w of per_window_records) {
    if (!w || !Array.isArray(w.per_sample_values)) continue;
    if (!(Number.isFinite(w.start_bp) && Number.isFinite(w.end_bp))) continue;
    if (!(w.start_bp < ce && w.end_bp > cs)) continue;
    n_windows++;
    for (let si = 0; si < n_samples; si++) {
      const v = w.per_sample_values[si];
      if (v != null && Number.isFinite(v) && v !== -1) {
        sums[si] += v; counts[si]++;
      }
    }
  }
  const means = new Array(n_samples);
  for (let si = 0; si < n_samples; si++) {
    means[si] = counts[si] > 0 ? sums[si] / counts[si] : NaN;
  }
  return { per_sample_means: means, n_windows };
}

// =====================================================================
// 2. Per-karyotype-group summary (median, IQR, n)
// =====================================================================

/**
 * Group a per-sample value array by karyotype and emit the
 * spec §2 summary per group.
 *
 * @param {Array<number>} per_sample_values
 * @param {Array<string|null>} karyotype_per_sample  one of KARYOTYPE_GROUPS
 *                                                   or null/missing
 * @returns {{ 'STD/STD':{n,median,iqr},
 *             'HET':{n,median,iqr},
 *             'INV/INV':{n,median,iqr} }}
 */
export function summarizeByKaryotype(per_sample_values, karyotype_per_sample) {
  const out = Object.create(null);
  const buckets = Object.create(null);
  for (const g of KARYOTYPE_GROUPS) buckets[g] = [];
  if (!Array.isArray(per_sample_values) || !Array.isArray(karyotype_per_sample)) {
    for (const g of KARYOTYPE_GROUPS) out[g] = { n: 0, median: NaN, iqr: [NaN, NaN] };
    return out;
  }
  const N = Math.min(per_sample_values.length, karyotype_per_sample.length);
  for (let si = 0; si < N; si++) {
    const g = karyotype_per_sample[si];
    const v = per_sample_values[si];
    if (g != null && buckets[g] && Number.isFinite(v)) {
      buckets[g].push(v);
    }
  }
  for (const g of KARYOTYPE_GROUPS) {
    out[g] = {
      n:      buckets[g].length,
      median: median(buckets[g]),
      iqr:    iqr(buckets[g]),
    };
  }
  return out;
}

// =====================================================================
// 3. Pairwise Wilcoxon
// =====================================================================

/**
 * Spec §2.3 — pairwise rank-sum tests: STD vs INV, STD vs HET, HET vs INV.
 *
 * Returns `{ std_vs_inv, std_vs_het, het_vs_inv }` where each is
 * `{ wilcoxon_p, delta_median }`. `wilcoxon_p = NaN` when either group
 * is empty / a single tie.
 */
export function pairwiseWilcoxonByKaryotype(per_sample_values, karyotype_per_sample) {
  const buckets = { 'STD/STD': [], 'HET': [], 'INV/INV': [] };
  const N = Math.min(
    per_sample_values ? per_sample_values.length : 0,
    karyotype_per_sample ? karyotype_per_sample.length : 0,
  );
  for (let si = 0; si < N; si++) {
    const g = karyotype_per_sample[si];
    const v = per_sample_values[si];
    if (buckets[g] && Number.isFinite(v)) buckets[g].push(v);
  }
  const pair = (a, b) => {
    const r = wilcoxonRankSumP(a, b);
    const ma = median(a), mb = median(b);
    return {
      wilcoxon_p:   r ? r.p_two_sided : NaN,
      delta_median: Number.isFinite(ma) && Number.isFinite(mb) ? mb - ma : NaN,
    };
  };
  return {
    std_vs_inv: pair(buckets['STD/STD'], buckets['INV/INV']),
    std_vs_het: pair(buckets['STD/STD'], buckets['HET']),
    het_vs_inv: pair(buckets['HET'],     buckets['INV/INV']),
  };
}

// =====================================================================
// 4. Verdict classification (spec §3 table)
// =====================================================================

/**
 * Map a (kw_p, pairwise, group-medians) triple to one of the
 * FUNCTIONAL_BURDEN_VERDICTS labels.
 *
 * Spec §3 decision table:
 *   - underpowered:    n_min < 5 in any group OR no kw_p
 *   - neutral:         kw_p ≥ 0.05 OR all-group medians within ±10%
 *   - inv_elevated:    INV median > STD median AND std_vs_inv p < 0.05
 *   - inv_depleted:    INV median < STD median AND std_vs_inv p < 0.05
 *   - heterosis_like:  HET median is lowest among the three
 *   - mixed:           two elevated + one depleted (rare)
 *
 * The order of checks matters: 'underpowered' precedes everything,
 * 'neutral' before the direction-checks (so a non-significant KW
 * never trips inv_*), and 'heterosis_like' before 'mixed' (it's a
 * more specific pattern).
 *
 * @param {{ groups:Object, kw_p:number, pairwise:Object }} args
 * @param {Object} [opts]
 * @returns {string}  one of FUNCTIONAL_BURDEN_VERDICTS values
 */
export function classifyMetricVerdict(args, opts) {
  const o = opts || {};
  const kwThresh  = Number.isFinite(o.kw_p_threshold) ? o.kw_p_threshold : FUNCTIONAL_BURDEN_DEFAULTS.kw_p_threshold;
  const eqPct     = Number.isFinite(o.median_equiv_pct) ? o.median_equiv_pct : FUNCTIONAL_BURDEN_DEFAULTS.median_equiv_pct;
  const pwThresh  = Number.isFinite(o.pairwise_p_threshold) ? o.pairwise_p_threshold : FUNCTIONAL_BURDEN_DEFAULTS.pairwise_p_threshold;
  const minN      = Number.isFinite(o.min_group_n) ? o.min_group_n : FUNCTIONAL_BURDEN_DEFAULTS.min_group_n;

  const g = (args && args.groups) || {};
  const std = g['STD/STD'] || {};
  const het = g['HET']     || {};
  const inv = g['INV/INV'] || {};
  const kw_p = args && args.kw_p;
  const pw = (args && args.pairwise) || {};

  // Underpowered first — overrides everything.
  if (std.n < minN || het.n < minN || inv.n < minN) {
    return FUNCTIONAL_BURDEN_VERDICTS.UNDERPOWERED;
  }
  if (!Number.isFinite(kw_p)) {
    return FUNCTIONAL_BURDEN_VERDICTS.UNDERPOWERED;
  }
  // Neutral.
  const mStd = std.median, mHet = het.median, mInv = inv.median;
  if (kw_p >= kwThresh) return FUNCTIONAL_BURDEN_VERDICTS.NEUTRAL;
  if (Number.isFinite(mStd) && Number.isFinite(mHet) && Number.isFinite(mInv)) {
    const med_avg = (Math.abs(mStd) + Math.abs(mHet) + Math.abs(mInv)) / 3;
    const span = Math.max(mStd, mHet, mInv) - Math.min(mStd, mHet, mInv);
    if (med_avg > 0 && span / med_avg <= eqPct) {
      return FUNCTIONAL_BURDEN_VERDICTS.NEUTRAL;
    }
  }
  // Heterosis: HET strictly lowest among the three.
  if (Number.isFinite(mStd) && Number.isFinite(mHet) && Number.isFinite(mInv)
      && mHet < mStd && mHet < mInv) {
    return FUNCTIONAL_BURDEN_VERDICTS.HETEROSIS_LIKE;
  }
  // Direction-of-inversion-effect from std_vs_inv pair.
  const sv = pw.std_vs_inv || {};
  if (Number.isFinite(sv.wilcoxon_p) && sv.wilcoxon_p < pwThresh
      && Number.isFinite(sv.delta_median)) {
    // delta_median = median(INV) - median(STD) by construction.
    if (sv.delta_median > 0) return FUNCTIONAL_BURDEN_VERDICTS.INV_ELEVATED;
    if (sv.delta_median < 0) return FUNCTIONAL_BURDEN_VERDICTS.INV_DEPLETED;
  }
  // Two elevated + one depleted = mixed.
  return FUNCTIONAL_BURDEN_VERDICTS.MIXED;
}

// =====================================================================
// 5. Composite per-candidate tag (spec §3)
// =====================================================================

/**
 * Roll up verdicts across the 4 burden metrics (πN/πS, VESM, LOF, ROH)
 * into a single per-candidate summary tag.
 *
 *   load_rich:   ≥ 3 of {πN/πS, VESM, LOF, ROH} = inv_elevated
 *   clean:       ≥ 3 = neutral
 *   mixed:       otherwise
 *
 * @param {Object} per_metric   keyed by metric name → row with `.verdict`
 * @returns {string}            one of FUNCTIONAL_BURDEN_TAGS values
 */
export function compositeSummaryTag(per_metric, opts) {
  const o = opts || {};
  const thr = Number.isFinite(o.tag_threshold) ? o.tag_threshold : FUNCTIONAL_BURDEN_DEFAULTS.tag_threshold;
  let elev = 0, neut = 0;
  for (const k of FUNCTIONAL_BURDEN_TAG_METRICS) {
    const v = per_metric && per_metric[k] && per_metric[k].verdict;
    if (v === FUNCTIONAL_BURDEN_VERDICTS.INV_ELEVATED) elev++;
    else if (v === FUNCTIONAL_BURDEN_VERDICTS.NEUTRAL) neut++;
  }
  if (elev >= thr) return FUNCTIONAL_BURDEN_TAGS.LOAD_RICH;
  if (neut >= thr) return FUNCTIONAL_BURDEN_TAGS.CLEAN;
  return FUNCTIONAL_BURDEN_TAGS.MIXED;
}

// =====================================================================
// 6. End-to-end summariser — single candidate, all metrics
// =====================================================================

/**
 * Spec §4 schema producer.
 *
 * Inputs:
 *   candidate              {candidate_id, chrom, start_bp, end_bp,
 *                           inversion_type?}
 *   per_window_layers      { metric_name → Array<window-record> }
 *   karyotype_per_sample   Array<'STD/STD'|'HET'|'INV/INV'|null>
 *   opts                   FUNCTIONAL_BURDEN_DEFAULTS overrides
 *
 * Output: an object matching spec §4 — per-metric row inside
 * `per_metric`, the composite `summary_tag`, and a `warnings` list
 * for missing layers.
 */
export function summarizeCandidateFunctionalBurden(
  candidate,
  per_window_layers,
  karyotype_per_sample,
  opts,
) {
  const o = opts || {};
  const out = {
    candidate_id:   candidate ? candidate.candidate_id : null,
    inversion_type: candidate ? (candidate.inversion_type || null) : null,
    chrom:          candidate ? (candidate.chrom || null) : null,
    start_bp:       candidate ? candidate.start_bp : null,
    end_bp:         candidate ? candidate.end_bp : null,
    summary_tag:    null,
    per_metric:     Object.create(null),
    warnings:       [],
    created_at:     new Date().toISOString(),
    module_version: FUNCTIONAL_BURDEN_MODULE_VERSION,
  };
  for (const metric of FUNCTIONAL_BURDEN_METRICS) {
    const layer = per_window_layers && per_window_layers[metric];
    if (!Array.isArray(layer) || layer.length === 0) {
      out.warnings.push(`missing layer: ${metric}`);
      out.per_metric[metric] = {
        groups: _emptyGroups(),
        kw_p: NaN,
        pairwise: _emptyPairwise(),
        verdict: FUNCTIONAL_BURDEN_VERDICTS.UNDERPOWERED,
        n_windows: 0,
      };
      continue;
    }
    const agg = aggregatePerSampleWithinCandidate(layer, candidate);
    const groups = summarizeByKaryotype(agg.per_sample_means, karyotype_per_sample);
    // Kruskal–Wallis across the three karyotype groups.
    const byGroup = { 'STD/STD': [], 'HET': [], 'INV/INV': [] };
    const N = Math.min(
      agg.per_sample_means.length,
      karyotype_per_sample ? karyotype_per_sample.length : 0,
    );
    for (let si = 0; si < N; si++) {
      const g = karyotype_per_sample[si];
      const v = agg.per_sample_means[si];
      if (byGroup[g] && Number.isFinite(v)) byGroup[g].push(v);
    }
    const kw = kruskalWallis([byGroup['STD/STD'], byGroup['HET'], byGroup['INV/INV']]);
    const kw_p = kw ? kw.p : NaN;
    const pairwise = pairwiseWilcoxonByKaryotype(
      agg.per_sample_means, karyotype_per_sample,
    );
    const verdict = classifyMetricVerdict({ groups, kw_p, pairwise }, o);
    out.per_metric[metric] = {
      groups, kw_p, pairwise, verdict, n_windows: agg.n_windows,
    };
  }
  out.summary_tag = compositeSummaryTag(out.per_metric, o);
  return out;
}

function _emptyGroups() {
  const o = Object.create(null);
  for (const g of KARYOTYPE_GROUPS) o[g] = { n: 0, median: NaN, iqr: [NaN, NaN] };
  return o;
}
function _emptyPairwise() {
  return {
    std_vs_inv: { wilcoxon_p: NaN, delta_median: NaN },
    std_vs_het: { wilcoxon_p: NaN, delta_median: NaN },
    het_vs_inv: { wilcoxon_p: NaN, delta_median: NaN },
  };
}

// =====================================================================
// 7. Homokaryotype-mode π reduction (overdominance disentangler)
// =====================================================================

/**
 * Compare π (or πS, or any per-sample diversity metric) between the
 * MOST-FREQUENT homokaryotype group and the all-karyotype pool.
 *
 * Captures the disentangling test from Faria et al. and related
 * inversion papers: if pooled π is maintained but π within the
 * most-frequent homokaryotype drops sharply (~40% in the reference
 * paper for catfish inversions), the cohort-level diversity is
 * partly carried by heterozygotes — overdominance / associative
 * overdominance compensating for the depression that low
 * recombination would otherwise cause.
 *
 * @param {Array<number>} per_sample_values    π (or πS) per sample
 * @param {Array<string|null>} karyotype_per_sample
 *   one of 'STD/STD' | 'HET' | 'INV/INV' | null/missing
 * @returns {{
 *   pi_all:                  number,   // mean across all called samples
 *   pi_mode_homokaryotype:   number,   // mean in the most-frequent
 *                                       // homokaryotype group
 *   mode_karyotype:          string,   // 'STD/STD' or 'INV/INV'
 *   fraction_reduction:      number,   // 1 - pi_mode / pi_all (NaN-safe)
 *   n_all:                   number,
 *   n_mode:                  number,
 * }|null}
 *
 * Returns null when there's no valid mode homokaryotype (e.g. only
 * heterozygotes present, or no called samples).
 */
export function compareHomokaryotypePiToAll(per_sample_values, karyotype_per_sample) {
  if (!Array.isArray(per_sample_values) || !Array.isArray(karyotype_per_sample)) return null;
  const N = Math.min(per_sample_values.length, karyotype_per_sample.length);
  if (N === 0) return null;

  let n_all = 0, sum_all = 0;
  const counts = { 'STD/STD': 0, 'HET': 0, 'INV/INV': 0 };
  const sums   = { 'STD/STD': 0, 'HET': 0, 'INV/INV': 0 };
  for (let i = 0; i < N; i++) {
    const v = per_sample_values[i];
    const g = karyotype_per_sample[i];
    if (!Number.isFinite(v)) continue;
    if (g !== 'STD/STD' && g !== 'HET' && g !== 'INV/INV') continue;
    sum_all += v; n_all++;
    sums[g]   += v; counts[g]++;
  }
  if (n_all === 0) return null;
  // Pick the most-frequent HOMOKARYOTYPE (not HET — HET is the alt class
  // we're contrasting against).
  const homAA = counts['STD/STD'];
  const homBB = counts['INV/INV'];
  if (homAA === 0 && homBB === 0) return null;
  const mode = homAA >= homBB ? 'STD/STD' : 'INV/INV';
  const n_mode = counts[mode];
  const pi_mode = n_mode > 0 ? sums[mode] / n_mode : NaN;
  const pi_all  = sum_all / n_all;
  const fraction_reduction = (Number.isFinite(pi_all) && pi_all !== 0)
    ? 1 - (pi_mode / pi_all) : NaN;
  return {
    pi_all,
    pi_mode_homokaryotype: pi_mode,
    mode_karyotype: mode,
    fraction_reduction,
    n_all,
    n_mode,
  };
}

/**
 * Sample-size control for the homokaryotype-mode π reduction
 * (compareHomokaryotypePiToAll above).
 *
 * The reduction observed when restricting to the most-frequent
 * homokaryotype could mechanically arise from the smaller sample
 * size, since π estimators are slightly biased downward at small n.
 * This subsamples the FULL cohort (all karyotypes pooled) down to
 * n_mode samples, recomputes π, and reports the bootstrap
 * distribution. If π_mode_homokaryotype is still significantly
 * below the subsampled distribution, the reduction is real and not
 * an n-effect (the paper's "we verified that these lower diversity
 * estimates were not simply a consequence of reduced sample size").
 *
 * @param {Array<number>} per_sample_values
 * @param {Array<string|null>} karyotype_per_sample
 * @param {{n_reps?:number, seed?:number}} [opts]
 *   n_reps: number of bootstrap subsamples (default 1000).
 *   seed:   optional u32 seed for the small mulberry32 PRNG below.
 *           Default = current Date.now() (non-deterministic; pass a
 *           seed when reproducibility matters).
 * @returns {{
 *   pi_mode_homokaryotype: number,    // copied from the compare fn
 *   n_mode:                number,
 *   subsampled_mean_pi:    number,    // mean π across n_reps subsamples
 *   subsampled_ci95:       [number, number],
 *   p_one_sided:           number,    // P(subsampled π ≤ pi_mode_homokaryotype)
 *   verdict:               'real_reduction' | 'consistent_with_sample_size' | 'inconclusive',
 *   n_reps:                number,
 * }|null}
 */
export function subsampleControlForHomokaryotypePi(per_sample_values, karyotype_per_sample, opts) {
  const cmp = compareHomokaryotypePiToAll(per_sample_values, karyotype_per_sample);
  if (!cmp) return null;
  const o = opts || {};
  const n_reps = Number.isFinite(o.n_reps) && o.n_reps > 0 ? o.n_reps : 1000;
  const n_mode = cmp.n_mode;
  // Pooled finite values across all karyotype groups.
  const pool = [];
  const N = Math.min(per_sample_values.length, karyotype_per_sample.length);
  for (let i = 0; i < N; i++) {
    const v = per_sample_values[i];
    const g = karyotype_per_sample[i];
    if (!Number.isFinite(v)) continue;
    if (g !== 'STD/STD' && g !== 'HET' && g !== 'INV/INV') continue;
    pool.push(v);
  }
  if (pool.length < 2 || n_mode < 2) {
    return {
      pi_mode_homokaryotype: cmp.pi_mode_homokaryotype,
      n_mode,
      subsampled_mean_pi: NaN,
      subsampled_ci95:    [NaN, NaN],
      p_one_sided:        NaN,
      verdict:            'inconclusive',
      n_reps:             0,
    };
  }
  const rng = _mulberry32(
    Number.isFinite(o.seed) ? (o.seed >>> 0) : (Date.now() >>> 0),
  );
  const samples = new Float64Array(n_reps);
  let countLE = 0;
  for (let r = 0; r < n_reps; r++) {
    let sum = 0;
    for (let i = 0; i < n_mode; i++) {
      sum += pool[Math.floor(rng() * pool.length)];
    }
    const mean = sum / n_mode;
    samples[r] = mean;
    if (mean <= cmp.pi_mode_homokaryotype) countLE++;
  }
  // CI from sorted subsamples.
  const sorted = Array.from(samples).sort((a, b) => a - b);
  const lo_idx = Math.floor(0.025 * n_reps);
  const hi_idx = Math.min(n_reps - 1, Math.floor(0.975 * n_reps));
  const ci95 = [sorted[lo_idx], sorted[hi_idx]];
  let mean = 0;
  for (let i = 0; i < n_reps; i++) mean += samples[i];
  mean /= n_reps;
  const p_one_sided = countLE / n_reps;
  let verdict;
  if (p_one_sided < 0.05) verdict = 'real_reduction';
  else if (p_one_sided > 0.5) verdict = 'consistent_with_sample_size';
  else verdict = 'inconclusive';
  return {
    pi_mode_homokaryotype: cmp.pi_mode_homokaryotype,
    n_mode,
    subsampled_mean_pi: mean,
    subsampled_ci95:    ci95,
    p_one_sided,
    verdict,
    n_reps,
  };
}

// Small deterministic PRNG for reproducible bootstrap. Mulberry32.
function _mulberry32(seed) {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6D2B79F5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
